export default {
  Appliance: [
    "Gros électroménager",
    "Petit électroménager",
    "Téléviseur",
    "Réfrigérateur",
    "Appareil photo numérique",
    "Informatique",
    "Micro-ondes",
  ],
  Bag: [
    "Sac en coton (tissu)",
    "Sac de course",
    "Sac plastique jetable",
    "Sac poubelle",
  ],
  Battery: [
    "Batterie",
    "Batterie automobile",
    "Pile jetable",
    "Pile rechargeable",
  ],
  Bike: ["Vélo"],
  Boat: ["Bateau"],
  Bottle: [
    "Bouteille en métal",
    "Bouteille en plastique",
    "Bouteille en verre",
  ],
  Box: [
    "Boîte en plastique",
    "Boîte à fromage en bois",
    "Boîte en métal",
    "Brique alimentaire",
    "Carton",
  ],
  Camera: ["Appareil photo numérique"],
  Can: ["Boîte de conserve", "Canette"],
  Car: ["Voiture"],
  Clothes: ["Chaussures", "Vêtement"],
  "Construction materials": ["Matériaux de construction"],
  Cup: ["Gobelet en carton", "Gobelet en plastique jetable"],
  Deodorant: ["Bombe aérosol"],
  "Egg Box": ["Boîte à oeufs en carton", "Boîte à oeufs en plastique"],
  "Fruits and vegetables": ["Fruits et légumes abîmés"],
  Furniture: ["Meuble"],
  "Ink cartridge": ["Cartouche d'encre"],
  Jewel: ["Bijou"],
  Light: ["Ampoule"],
  Lighter: ["Briquet"],
  Medication: ["Médicaments"],
  Paper: ["Journal", "Cahier", "Papier", "Livre"],
  Pen: ["Feutre", "Stylo", "Crayon en bois"],
  Phone: ["Téléphone mobile"],
  Plants: ["Déchets verts"],
  "Plastic cap": ["Bouchons en plastique"],
  "Q-tip": ["Coton-tige"],
  Shaver: ["Rasoir jetable"],
  "Surgical mask": ["Masque à usage unique"],
  Tissue: ["Mouchoir en papier", "Essuie-tout"],
  Toothpaste: ["Tube de dentifrice"],
  Tray: ["Barquette en aluminium", "Barquette en plastique"],
  Tyre: ["Pneu"],
};
