export default {
  Aerosol: {
    nom: "Aerosol",
    fiche: "Bombe aérosol",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/aerosol.png",
    synonyme: "",
  },
  "Album de musique": {
    nom: "Album de musique",
    fiche: "CD/DVD",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/album-de-musique.png",
    synonyme: "Blu-ray / CD-ROM / Disque (album) / CD / DVD / CDRom / Cassette",
  },
  Ampoule: {
    nom: "Ampoule",
    fiche: "Ampoule",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/ampoule.png",
    synonyme: "Lampe",
  },
  "Anti-cernes": {
    nom: "Anti-cernes",
    fiche: "Cosmétique (produit et emballage)",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/anti-cernes.png",
    synonyme: "",
  },
  "Appareil photo": {
    nom: "Appareil photo",
    fiche: "Appareil photo numérique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/appareil-photo.png",
    synonyme: "",
  },
  Armoire: {
    nom: "Armoire",
    fiche: "Meuble",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/armoire.png",
    synonyme: "",
  },
  Aspirateur: {
    nom: "Aspirateur",
    fiche: "Gros électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/aspirateur.png",
    synonyme: "",
  },
  Assiette: {
    nom: "Assiette",
    fiche: "Vaisselle",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/assiette.png",
    synonyme: "",
  },
  Banc: {
    nom: "Banc",
    fiche: "Meuble",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/banc.png",
    synonyme: "",
  },
  "Bande-dessinée": {
    nom: "Bande-dessinée",
    fiche: "Livre",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/bande-dessinée.png",
    synonyme: "BD",
  },
  "Barquette en aluminium": {
    nom: "Barquette en aluminium",
    fiche: "Barquette en aluminium",
    icone:
      "https://oncle-stan.pacifiscan.org/icon-v2/barquette-en-aluminium.png",
    synonyme: "",
  },
  "Barquette en plastique": {
    nom: "Barquette en plastique",
    fiche: "Barquette en plastique",
    icone:
      "https://oncle-stan.pacifiscan.org/icon-v2/barquette-en-plastique.png",
    synonyme: "",
  },
  "Bateau à moteur": {
    nom: "Bateau à moteur",
    fiche: "Bateau",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/bateau-à-moteur.png",
    synonyme: "",
  },
  Batterie: {
    nom: "Batterie",
    fiche: "Batterie",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/batterie.png",
    synonyme: "",
  },
  "Batterie automobile": {
    nom: "Batterie automobile",
    fiche: "Batterie automobile",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/batterie-automobile.png",
    synonyme: "",
  },
  Béton: {
    nom: "Béton",
    fiche: "Matériaux de construction",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/béton.png",
    synonyme: "",
  },
  "Biberon en plastique": {
    nom: "Biberon en plastique",
    fiche: "Biberon en plastique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/biberon-en-plastique.png",
    synonyme: "",
  },
  Bibliothèque: {
    nom: "Bibliothèque",
    fiche: "Meuble",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/bibliothèque.png",
    synonyme: "",
  },
  "Bidon d'huile de moteur": {
    nom: "Bidon d'huile de moteur",
    fiche: "Bidon d'huile de moteur",
    icone:
      "https://oncle-stan.pacifiscan.org/icon-v2/bidon-d'huile-de-moteur.png",
    synonyme: "",
  },
  "Bidon de lessive": {
    nom: "Bidon de lessive",
    fiche: "Bouteille en plastique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/bidon-de-lessive.png",
    synonyme: "",
  },
  "Bloc-notes": {
    nom: "Bloc-notes",
    fiche: "Cahier",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/bloc-notes.png",
    synonyme: "",
  },
  Blush: {
    nom: "Blush",
    fiche: "Cosmétique (produit et emballage)",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/blush.png",
    synonyme: "",
  },
  "Bocal en verre": {
    nom: "Bocal en verre",
    fiche: "Bocal en verre",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/bocal-en-verre.png",
    synonyme: "",
  },
  Bois: {
    nom: "Bois",
    fiche: "Bois",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/bois.png",
    synonyme: "",
  },
  "Boite à œufs en carton": {
    nom: "Boite à œufs en carton",
    fiche: "Boîte à oeufs en carton",
    icone:
      "https://oncle-stan.pacifiscan.org/icon-v2/boite-à-œufs-en-carton.png",
    synonyme: "",
  },
  "Boîte à œufs en plastique": {
    nom: "Boîte à œufs en plastique",
    fiche: "Boîte à oeufs en plastique",
    icone:
      "https://oncle-stan.pacifiscan.org/icon-v2/boîte-à-œufs-en-plastique.png",
    synonyme: "",
  },
  "Boîte de conserve": {
    nom: "Boîte de conserve",
    fiche: "Boîte de conserve",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/boîte-de-conserve.png",
    synonyme: "",
  },
  "Boîte en carton": {
    nom: "Boîte en carton",
    fiche: "Carton",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/boîte-en-carton.png",
    synonyme: "",
  },
  "Boîte en métal": {
    nom: "Boîte en métal",
    fiche: "Boîte en métal",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/boîte-en-métal.png",
    synonyme: "",
  },
  "Boîte en plastique": {
    nom: "Boîte en plastique",
    fiche: "Boîte en plastique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/boîte-en-plastique.png",
    synonyme: "",
  },
  Bol: {
    nom: "Bol",
    fiche: "Vaisselle",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/bol.png",
    synonyme: "",
  },
  "Bombe insecticide": {
    nom: "Bombe insecticide",
    fiche: "Bombe aérosol",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/bombe-insecticide.png",
    synonyme: "",
  },
  Bonnet: {
    nom: "Bonnet",
    fiche: "Vêtement",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/bonnet.png",
    synonyme: "",
  },
  "Bouchon en plastique": {
    nom: "Bouchon en plastique",
    fiche: "Bouchons en plastique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/bouchon-en-plastique.png",
    synonyme: "",
  },
  "Boucles d'oreille": {
    nom: "Boucles d'oreille",
    fiche: "Bijou",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/boucles-d'oreille.png",
    synonyme: "",
  },
  Bougie: {
    nom: "Bougie",
    fiche: "Bougie",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/bougie.png",
    synonyme: "Chandelle",
  },
  Bouilloire: {
    nom: "Bouilloire",
    fiche: "Petit électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/bouilloire.png",
    synonyme: "",
  },
  "Bouteille d'eau": {
    nom: "Bouteille d'eau",
    fiche: "Bouteille en plastique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/bouteille-d'eau.png",
    synonyme: "",
  },
  "Bouteille de gaz": {
    nom: "Bouteille de gaz",
    fiche: "Bouteille de gaz",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/bouteille-de-gaz.png",
    synonyme: "",
  },
  "Bouteille en verre": {
    nom: "Bouteille en verre",
    fiche: "Bouteille en verre",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/bouteille-en-verre.png",
    synonyme: "",
  },
  "Bouteille en métal": {
    nom: "Bouteille en métal",
    fiche: "Bouteille en métal",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/bouteille-en-métal.png",
    synonyme: "Bouteille de sirop",
  },
  "Bouteille en plastique": {
    nom: "Bouteille en plastique",
    fiche: "Bouteille en plastique",
    icone:
      "https://oncle-stan.pacifiscan.org/icon-v2/bouteille-en-plastique.png",
    synonyme: "",
  },
  "Box internet": {
    nom: "Box internet",
    fiche: "Informatique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/box-internet.png",
    synonyme: "",
  },
  Bracelet: {
    nom: "Bracelet",
    fiche: "Bijou",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/bracelet.png",
    synonyme: "",
  },
  Brique: {
    nom: "Brique",
    fiche: "Matériaux de construction",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/brique.png",
    synonyme: "",
  },
  "Brique de jus de fruit": {
    nom: "Brique de jus de fruit",
    fiche: "Brique alimentaire",
    icone:
      "https://oncle-stan.pacifiscan.org/icon-v2/brique-de-jus-de-fruit.png",
    synonyme: "",
  },
  "Brique de lait": {
    nom: "Brique de lait",
    fiche: "Brique alimentaire",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/brique-de-lait.png",
    synonyme: "",
  },
  Briquet: {
    nom: "Briquet",
    fiche: "Briquet",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/briquet.png",
    synonyme: "",
  },
  "Brosse à dent": {
    nom: "Brosse à dent",
    fiche: "Brosse à dents",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/brosse-à-dent.png",
    synonyme: "",
  },
  Brumisateur: {
    nom: "Brumisateur",
    fiche: "Bombe aérosol",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/brumisateur.png",
    synonyme: "",
  },
  Cafetière: {
    nom: "Cafetière",
    fiche: "Petit électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/cafetière.png",
    synonyme: "",
  },
  Cahier: {
    nom: "Cahier",
    fiche: "Cahier",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/cahier.png",
    synonyme: "",
  },
  Calendrier: {
    nom: "Calendrier",
    fiche: "Cahier",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/calendrier.png",
    synonyme: "",
  },
  Caméra: {
    nom: "Caméra",
    fiche: "Appareil photo numérique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/caméra.png",
    synonyme: "",
  },
  Canapé: {
    nom: "Canapé",
    fiche: "Meuble",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/canapé.png",
    synonyme: "",
  },
  Canette: {
    nom: "Canette",
    fiche: "Canette",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/canette.png",
    synonyme: "",
  },
  "Capsule de café": {
    nom: "Capsule de café",
    fiche: "Capsules de café ou de thé",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/capsule-de-café.png",
    synonyme: "",
  },
  Carnet: {
    nom: "Carnet",
    fiche: "Cahier",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/carnet.png",
    synonyme: "",
  },
  Carrelage: {
    nom: "Carrelage",
    fiche: "Matériaux de construction",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/carrelage.png",
    synonyme: "",
  },
  "Carte bancaire": {
    nom: "Carte bancaire",
    fiche: "Carte à puce (bancaire, de téléphone, d'identité)",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/carte-bancaire.png",
    synonyme: "",
  },
  "Carte RFID": {
    nom: "Carte RFID",
    fiche: "Carte à puce (bancaire, de téléphone, d'identité)",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/carte-rfid.png",
    synonyme: "",
  },
  "Carte SIM": {
    nom: "Carte SIM",
    fiche: "Carte à puce (bancaire, de téléphone, d'identité)",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/carte-sim.png",
    synonyme: "",
  },
  "Cartouche d'encre": {
    nom: "Cartouche d'encre",
    fiche: "Cartouche d'encre",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/cartouche-d'encre.png",
    synonyme: "",
  },
  Casserolle: {
    nom: "Casserolle",
    fiche: "Casserole",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/casserolle.png",
    synonyme: "",
  },
  "CD/DVD": {
    nom: "CD/DVD",
    fiche: "CD/DVD",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/cd-dvd.png",
    synonyme: "Blu-ray / CD-ROM / Disque (album) / CD / DVD / CDRom / Cassette",
  },
  "Chaîne hi-fi": {
    nom: "Chaîne hi-fi",
    fiche: "Petit électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/chaîne-hi-fi.png",
    synonyme: "",
  },
  Chaise: {
    nom: "Chaise",
    fiche: "Meuble",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/chaise.png",
    synonyme: "",
  },
  Chaussure: {
    nom: "Chaussure",
    fiche: "Chaussures",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/chaussure.png",
    synonyme:
      "Bottes / Bottines / Baskets / Tennis / Chaussons / Pantoufles / Savattes / Souliers / Après-ski / Babouches / Ballerines / Boots / Escarpins / Mocassins / Nu-pieds / Tongs / Sabots / Sandales / Snow-boot / Ballerines",
  },
  Chemise: {
    nom: "Chemise",
    fiche: "Vêtement",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/chemise.png",
    synonyme: "",
  },
  "Chewing-gum": {
    nom: "Chewing-gum",
    fiche: "Chewing-gum",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/chewing-gum.png",
    synonyme: "Bubble-gum",
  },
  "Cigarette électronique": {
    nom: "Cigarette électronique",
    fiche: "Cigarette électronique",
    icone:
      "https://oncle-stan.pacifiscan.org/icon-v2/cigarette-électronique.png",
    synonyme: "",
  },
  Ciseau: {
    nom: "Ciseau",
    fiche: "Matériel scolaire en plastique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/ciseau.png",
    synonyme: "",
  },
  Clavier: {
    nom: "Clavier",
    fiche: "Informatique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/clavier.png",
    synonyme: "",
  },
  "Clé USB": {
    nom: "Clé USB",
    fiche: "Informatique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/clé-usb.png",
    synonyme: "",
  },
  Climatiseur: {
    nom: "Climatiseur",
    fiche: "Gros électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/climatiseur.png",
    synonyme: "",
  },
  Coffre: {
    nom: "Coffre",
    fiche: "Meuble",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/coffre.png",
    synonyme: "",
  },
  Collier: {
    nom: "Collier",
    fiche: "Bijou",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/collier.png",
    synonyme: "",
  },
  Commode: {
    nom: "Commode",
    fiche: "Meuble",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/commode.png",
    synonyme: "",
  },
  "Composant informatique": {
    nom: "Composant informatique",
    fiche: "Informatique",
    icone:
      "https://oncle-stan.pacifiscan.org/icon-v2/composant-informatique.png",
    synonyme: "",
  },
  Congélateur: {
    nom: "Congélateur",
    fiche: "Gros électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/congélateur.png",
    synonyme: "",
  },
  "Console de jeu": {
    nom: "Console de jeu",
    fiche: "Informatique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/console-de-jeu.png",
    synonyme: "",
  },
  "Coquille d'œufs": {
    nom: "Coquille d'œufs",
    fiche: "Coquilles d'oeufs",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/coquille-d'œufs.png",
    synonyme: "œufs",
  },
  "Coton-tige": {
    nom: "Coton-tige",
    fiche: "Coton-tige",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/coton-tige.png",
    synonyme: "",
  },
  "Couche-culotte": {
    nom: "Couche-culotte",
    fiche: "Couche-culotte",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/couche-culotte.png",
    synonyme:
      "Couches pour bébé / Couche pour fuite urinaire / Couche hygiénique",
  },
  Couteau: {
    nom: "Couteau",
    fiche: "Couverts",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/couteau.png",
    synonyme: "",
  },
  "Crayon à papier": {
    nom: "Crayon à papier",
    fiche: "Crayon à papier",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/crayon-à-papier.png",
    synonyme: "Crayon de couleur",
  },
  Cuillère: {
    nom: "Cuillère",
    fiche: "Couverts",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/cuillère.png",
    synonyme: "",
  },
  Déodorant: {
    nom: "Déodorant",
    fiche: "Bombe aérosol",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/déodorant.png",
    synonyme: "",
  },
  "Disque dur externe": {
    nom: "Disque dur externe",
    fiche: "Informatique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/disque-dur-externe.png",
    synonyme: "",
  },
  "Eau de javel en bouteille": {
    nom: "Eau de javel en bouteille",
    fiche: "Bouteille en plastique",
    icone:
      "https://oncle-stan.pacifiscan.org/icon-v2/eau-de-javel-en-bouteille.png",
    synonyme: "",
  },
  Ecouteurs: {
    nom: "Ecouteurs",
    fiche: "Informatique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/ecouteurs.png",
    synonyme: "",
  },
  Epluchures: {
    nom: "Epluchures",
    fiche: "Aliments compostables",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/epluchures.png",
    synonyme: "",
  },
  "Essuie-tout": {
    nom: "Essuie-tout",
    fiche: "Essuie-tout",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/essuie-tout.png",
    synonyme: "",
  },
  Etagère: {
    nom: "Etagère",
    fiche: "Meuble",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/etagère.png",
    synonyme: "",
  },
  Eyeliner: {
    nom: "Eyeliner",
    fiche: "Cosmétique (produit et emballage)",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/eyeliner.png",
    synonyme: "",
  },
  "Fard à paupières": {
    nom: "Fard à paupières",
    fiche: "Cosmétique (produit et emballage)",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/fard-à-paupières.png",
    synonyme: "",
  },
  Fauteuil: {
    nom: "Fauteuil",
    fiche: "Meuble",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/fauteuil.png",
    synonyme: "",
  },
  Fenêtre: {
    nom: "Fenêtre",
    fiche: "Matériaux de construction",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/fenêtre.png",
    synonyme: "",
  },
  "Fer à repasser": {
    nom: "Fer à repasser",
    fiche: "Petit électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/fer-à-repasser.png",
    synonyme: "",
  },
  "Feuilles vertes": {
    nom: "Feuilles vertes",
    fiche: "Déchets verts",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/feuilles-vertes.png",
    synonyme: "",
  },
  Feutres: {
    nom: "Feutres",
    fiche: "Stylo",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/feutres.png",
    synonyme: "",
  },
  Figurine: {
    nom: "Figurine",
    fiche: "Jouet",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/figurine.png",
    synonyme: "",
  },
  "Film plastique": {
    nom: "Film plastique",
    fiche: "Film plastique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/film-plastique.png",
    synonyme: "",
  },
  "Filtre à café": {
    nom: "Filtre à café",
    fiche: "Filtre à café",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/filtre-à-café.png",
    synonyme: "",
  },
  "Flacon en plastique": {
    nom: "Flacon en plastique",
    fiche: "Flacon en plastique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/flacon-en-plastique.png",
    synonyme: "",
  },
  "Fleurs fanées": {
    nom: "Fleurs fanées",
    fiche: "Déchets verts",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/fleurs-fanées.png",
    synonyme: "",
  },
  "Fond de teint": {
    nom: "Fond de teint",
    fiche: "Cosmétique (produit et emballage)",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/fond-de-teint.png",
    synonyme: "",
  },
  Four: {
    nom: "Four",
    fiche: "Gros électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/four.png",
    synonyme: "",
  },
  Fourchette: {
    nom: "Fourchette",
    fiche: "Couverts",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/fourchette.png",
    synonyme: "",
  },
  Friteuse: {
    nom: "Friteuse",
    fiche: "Petit électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/friteuse.png",
    synonyme: "",
  },
  Fromage: {
    nom: "Fromage",
    fiche: "Aliments compostables",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/fromage.png",
    synonyme: "Camembert, Fromage de chèvre, Emmental, Gruyère",
  },
  "Fruit et légume": {
    nom: "Fruit et légume",
    fiche: "Aliments compostables",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/fruit-et-légume.png",
    synonyme:
      "Poireaux / Fenouils / Carottes / Navets / Pommes de terre / Aubergines / Courgettes / Pommes / Oranges / Litchis / Bananes / Poires / Fraises / Framboises / Mandarine / Clémentine",
  },
  Gilet: {
    nom: "Gilet",
    fiche: "Vêtement",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/gilet.png",
    synonyme: "",
  },
  "Gobelet en carton": {
    nom: "Gobelet en carton",
    fiche: "Gobelet en carton",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/gobelet-en-carton.png",
    synonyme: "Verre",
  },
  "Gobelet en plastique": {
    nom: "Gobelet en plastique",
    fiche: "Gobelet en plastique jetable",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/gobelet-en-plastique.png",
    synonyme: "Verre",
  },
  Gomme: {
    nom: "Gomme",
    fiche: "Matériel scolaire en plastique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/gomme.png",
    synonyme: "",
  },
  "Grille-pain": {
    nom: "Grille-pain",
    fiche: "Petit électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/grille-pain.png",
    synonyme: "",
  },
  "Haut-parleur": {
    nom: "Haut-parleur",
    fiche: "Informatique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/haut-parleur.png",
    synonyme: "",
  },
  "Huile de friture": {
    nom: "Huile de friture",
    fiche: "Huile de friture",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/huile-de-friture.png",
    synonyme: "",
  },
  "Jeu vidéo": {
    nom: "Jeu vidéo",
    fiche: "Jeu vidéo (cassette ou cartouche DS, PS3, Xbox...)",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/jeu-vidéo.png",
    synonyme: "",
  },
  Jouet: {
    nom: "Jouet",
    fiche: "Jouet",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/jouet.png",
    synonyme: "",
  },
  Journal: {
    nom: "Journal",
    fiche: "Journal",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/journal.png",
    synonyme: "",
  },
  Joystick: {
    nom: "Joystick",
    fiche: "Informatique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/joystick.png",
    synonyme: "",
  },
  "Lampe torche": {
    nom: "Lampe torche",
    fiche: "Petit électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/lampe-torche.png",
    synonyme: "Lumière",
  },
  "Lave-linge": {
    nom: "Lave-linge",
    fiche: "Gros électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/lave-linge.png",
    synonyme: "Machine à valer",
  },
  "Lave-vaisselle": {
    nom: "Lave-vaisselle",
    fiche: "Gros électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/lave-vaisselle.png",
    synonyme: "",
  },
  Lit: {
    nom: "Lit",
    fiche: "Meuble",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/lit.png",
    synonyme: "",
  },
  Livre: {
    nom: "Livre",
    fiche: "Livre",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/livre.png",
    synonyme: "Roman / Thriller / Romance ",
  },
  "Machine à coudre": {
    nom: "Machine à coudre",
    fiche: "Petit électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/machine-à-coudre.png",
    synonyme: "",
  },
  Magazine: {
    nom: "Magazine",
    fiche: "Journal",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/magazine.png",
    synonyme: "Revue",
  },
  "Maillot de bain": {
    nom: "Maillot de bain",
    fiche: "Vêtement",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/maillot-de-bain.png",
    synonyme: "",
  },
  Manga: {
    nom: "Manga",
    fiche: "Livre",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/manga.png",
    synonyme: "",
  },
  "Marc de café": {
    nom: "Marc de café",
    fiche: "Aliments compostables",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/marc-de-café.png",
    synonyme: "",
  },
  Mascara: {
    nom: "Mascara",
    fiche: "Cosmétique (produit et emballage)",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/mascara.png",
    synonyme: "",
  },
  "Masque chirurgical": {
    nom: "Masque chirurgical",
    fiche: "Masque à usage unique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/masque-chirurgical.png",
    synonyme: "",
  },
  Matelas: {
    nom: "Matelas",
    fiche: "Matelas (en mousse, à ressorts...)",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/matelas.png",
    synonyme: "",
  },
  Médicaments: {
    nom: "Médicaments",
    fiche: "Médicaments",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/médicaments.png",
    synonyme:
      "Sirop de médicament / Gélules de médicament / Comprimés de médicament / Médocs / Suppositoire / Pommade de médicament / Crème de médicament / Collyre / Pillule de médicament / Cachet de médicament / Spray de médicament / Gouttes de médicament / Patch de médicament / Doliprane",
  },
  "Mégot de cigarette": {
    nom: "Mégot de cigarette",
    fiche: "Mégot de cigarette",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/mégot-de-cigarette.png",
    synonyme: "",
  },
  "Micro-ondes": {
    nom: "Micro-ondes",
    fiche: "Petit électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/micro-ondes.png",
    synonyme: "Mini-four",
  },
  Microphone: {
    nom: "Microphone",
    fiche: "Informatique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/microphone.png",
    synonyme: "",
  },
  Mixeur: {
    nom: "Mixeur",
    fiche: "Petit électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/mixeur.png",
    synonyme: "",
  },
  "Moniteur PC": {
    nom: "Moniteur PC",
    fiche: "Téléviseur",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/moniteur-pc.png",
    synonyme: "",
  },
  Montre: {
    nom: "Montre",
    fiche: "Bijou",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/montre.png",
    synonyme: "",
  },
  Moto: {
    nom: "Moto",
    fiche: "Voiture",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/moto.png",
    synonyme: "Scooter, dirt",
  },
  "Mouchoir en papier": {
    nom: "Mouchoir en papier",
    fiche: "Mouchoir en papier",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/mouchoir-en-papier.png",
    synonyme: "Kleenex",
  },
  Néon: {
    nom: "Néon",
    fiche: "Ampoule",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/néon.png",
    synonyme: "Lampe",
  },
  "Opercule en métal": {
    nom: "Opercule en métal",
    fiche: "Opercule en alu / métal",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/opercule-en-métal.png",
    synonyme: "",
  },
  "Opercule en plastique": {
    nom: "Opercule en plastique",
    fiche: "Opercule en plastique",
    icone:
      "https://oncle-stan.pacifiscan.org/icon-v2/opercule-en-plastique.png",
    synonyme: "",
  },
  "Ordinateur fixe": {
    nom: "Ordinateur fixe",
    fiche: "Informatique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/ordinateur-fixe.png",
    synonyme: "",
  },
  "Ordinateur portable": {
    nom: "Ordinateur portable",
    fiche: "Informatique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/ordinateur-portable.png",
    synonyme: "PC portable",
  },
  "Palette en bois": {
    nom: "Palette en bois",
    fiche: "Palette en bois",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/palette-en-bois.png",
    synonyme: "",
  },
  Pantalon: {
    nom: "Pantalon",
    fiche: "Vêtement",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/pantalon.png",
    synonyme: "",
  },
  Papier: {
    nom: "Papier",
    fiche: "Papier",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/papier.png",
    synonyme: "Feuille",
  },
  "Papier aluminium": {
    nom: "Papier aluminium",
    fiche: "Papier aluminium",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/papier-aluminium.png",
    synonyme: "",
  },
  Peluche: {
    nom: "Peluche",
    fiche: "Jouet",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/peluche.png",
    synonyme: "",
  },
  "Pièce automobile": {
    nom: "Pièce automobile",
    fiche: "Pièce automobile",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/pièce-automobile.png",
    synonyme:
      "Moteur / Arbre à came / Transmission / Boite de vitesse / Chaîne de transmission / Phares / Carosserie / Frein",
  },
  Piercing: {
    nom: "Piercing",
    fiche: "Bijou",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/piercing.png",
    synonyme: "",
  },
  "Pile jetable": {
    nom: "Pile jetable",
    fiche: "Pile jetable",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/pile-jetable.png",
    synonyme: "",
  },
  "Pile rechargeable": {
    nom: "Pile rechargeable",
    fiche: "Pile rechargeable",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/pile-rechargeable.png",
    synonyme: "",
  },
  Placard: {
    nom: "Placard",
    fiche: "Meuble",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/placard.png",
    synonyme: "",
  },
  "Plaque de cuisson": {
    nom: "Plaque de cuisson",
    fiche: "Gros électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/plaque-de-cuisson.png",
    synonyme: "",
  },
  Pneu: {
    nom: "Pneu",
    fiche: "Pneu",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/pneu.png",
    synonyme: "Roue / Pneumatique",
  },
  Poele: {
    nom: "Poele",
    fiche: "Casserole",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/poele.png",
    synonyme: "",
  },
  Poisson: {
    nom: "Poisson",
    fiche: "Aliments compostables",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/poisson.png",
    synonyme: "Thon, Saumon, Maquerau, Sardine, Colin, Poisson pané",
  },
  "Porte-mines": {
    nom: "Porte-mines",
    fiche: "Stylo",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/porte-mines.png",
    synonyme: "Critérium",
  },
  "Pot de crème": {
    nom: "Pot de crème",
    fiche: "Pot en plastique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/pot-de-crème.png",
    synonyme: "",
  },
  "Pot de yahourt": {
    nom: "Pot de yahourt",
    fiche: "Pot en plastique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/pot-de-yahourt.png",
    synonyme: "",
  },
  Poudre: {
    nom: "Poudre",
    fiche: "Cosmétique (produit et emballage)",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/poudre.png",
    synonyme: "",
  },
  Préservatif: {
    nom: "Préservatif",
    fiche: "Préservatif",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/préservatif.png",
    synonyme: "Capote",
  },
  Pull: {
    nom: "Pull",
    fiche: "Vêtement",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/pull.png",
    synonyme: "Sweat, cardign",
  },
  "Radio-réveil": {
    nom: "Radio-réveil",
    fiche: "Petit électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/radio-réveil.png",
    synonyme: "",
  },
  "Rasoir jetable": {
    nom: "Rasoir jetable",
    fiche: "Rasoir jetable",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/rasoir-jetable.png",
    synonyme: "",
  },
  Réfrigérateur: {
    nom: "Réfrigérateur",
    fiche: "Gros électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/réfrigérateur.png",
    synonyme: "Frigo / Frigidaire",
  },
  "Règle, Equerre": {
    nom: "Règle, Equerre",
    fiche: "Matériel scolaire en plastique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/règle,-equerre.png",
    synonyme: "",
  },
  "Résidus de débrousaillement": {
    nom: "Résidus de débrousaillement",
    fiche: "Déchets verts",
    icone:
      "https://oncle-stan.pacifiscan.org/icon-v2/résidus-de-débrousaillement.png",
    synonyme: "",
  },
  "Aspirateur Robot": {
    nom: "Aspirateur Robot",
    fiche: "Petit électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/aspirateur-robot.png",
    synonyme: "",
  },
  "Rouge à lèvre": {
    nom: "Rouge à lèvre",
    fiche: "Rouge à lèvres",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/rouge-à-lèvre.png",
    synonyme: "",
  },
  "Ruban adhésif": {
    nom: "Ruban adhésif",
    fiche: "Matériel scolaire en plastique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/ruban-adhésif.png",
    synonyme: "Scotch",
  },
  "Sac cabas": {
    nom: "Sac cabas",
    fiche: "Sac de course",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/sac-cabas.png",
    synonyme: "Sac de course",
  },
  "Sac en tissu": {
    nom: "Sac en tissu",
    fiche: "Sac en coton (tissu)",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/sac-en-tissu.png",
    synonyme: "Tote bag",
  },
  "Sac plastique jetable": {
    nom: "Sac plastique jetable",
    fiche: "Sac plastique jetable",
    icone:
      "https://oncle-stan.pacifiscan.org/icon-v2/sac-plastique-jetable.png",
    synonyme: "",
  },
  "Sac poubelle": {
    nom: "Sac poubelle",
    fiche: "Sac poubelle",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/sac-poubelle.png",
    synonyme: "",
  },
  "Sachet de thé": {
    nom: "Sachet de thé",
    fiche: "Aliments compostables",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/sachet-de-thé.png",
    synonyme: "",
  },
  Scanner: {
    nom: "Scanner",
    fiche: "Informatique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/scanner.png",
    synonyme: "",
  },
  "Sèche-cheveux": {
    nom: "Sèche-cheveux",
    fiche: "Petit électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/sèche-cheveux.png",
    synonyme: "",
  },
  "Sèche-linge": {
    nom: "Sèche-linge",
    fiche: "Gros électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/sèche-linge.png",
    synonyme: "",
  },
  "Souris informatique": {
    nom: "Souris informatique",
    fiche: "Informatique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/souris-informatique.png",
    synonyme: "",
  },
  "Sous-vêtement": {
    nom: "Sous-vêtement",
    fiche: "Vêtement",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/sous-vêtement.png",
    synonyme: "Culotte, slip, caleçon, String, Tanga, Boxer",
  },
  Stylo: {
    nom: "Stylo",
    fiche: "Stylo",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/stylo.png",
    synonyme: "Bic",
  },
  "T-shirt": {
    nom: "T-shirt",
    fiche: "Vêtement",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/t-shirt.png",
    synonyme: "Débardeur",
  },
  Table: {
    nom: "Table",
    fiche: "Meuble",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/table.png",
    synonyme: "",
  },
  "Table basse": {
    nom: "Table basse",
    fiche: "Meuble",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/table-basse.png",
    synonyme: "",
  },
  Tablette: {
    nom: "Tablette",
    fiche: "Informatique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/tablette.png",
    synonyme: "",
  },
  "Taille crayon": {
    nom: "Taille crayon",
    fiche: "Matériel scolaire en plastique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/taille-crayon.png",
    synonyme: "",
  },
  "Taille de haies": {
    nom: "Taille de haies",
    fiche: "Déchets verts",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/taille-de-haies.png",
    synonyme: "",
  },
  Tasse: {
    nom: "Tasse",
    fiche: "Vaisselle",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/tasse.png",
    synonyme: "Bol",
  },
  Télécommande: {
    nom: "Télécommande",
    fiche: "Petit électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/télécommande.png",
    synonyme: "",
  },
  Téléphone: {
    nom: "Téléphone",
    fiche: "Téléphone mobile",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/téléphone.png",
    synonyme: "iPhone / Samsung Galaxy / Smartphone / Téléphone intelligent ",
  },
  Télévision: {
    nom: "Télévision",
    fiche: "Téléviseur",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/télévision.png",
    synonyme: "Téléviseur",
  },
  "Tetra pak": {
    nom: "Tetra pak",
    fiche: "Brique alimentaire",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/tetra-pak.png",
    synonyme: "Jus de fruit, Brique de lait, ",
  },
  "Tonte de pelouse": {
    nom: "Tonte de pelouse",
    fiche: "Déchets verts",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/tonte-de-pelouse.png",
    synonyme: "Herbe, tondeuse",
  },
  "Tube de colle": {
    nom: "Tube de colle",
    fiche: "Matériel scolaire en plastique",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/tube-de-colle.png",
    synonyme: "",
  },
  "Tube de crème": {
    nom: "Tube de crème",
    fiche: "Tube de dentifrice",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/tube-de-crème.png",
    synonyme: "",
  },
  "Tube de dentifrice": {
    nom: "Tube de dentifrice",
    fiche: "Tube de dentifrice",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/tube-de-dentifrice.png",
    synonyme: "",
  },
  Tuile: {
    nom: "Tuile",
    fiche: "Matériaux de construction",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/tuile.png",
    synonyme: "",
  },
  Vélo: {
    nom: "Vélo",
    fiche: "Vélo",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/vélo.png",
    synonyme: "",
  },
  Ventilateur: {
    nom: "Ventilateur",
    fiche: "Petit électroménager",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/ventilateur.png",
    synonyme: "",
  },
  Vêtement: {
    nom: "Vêtement",
    fiche: "Vêtement",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/vêtement.png",
    synonyme: "",
  },
  Viande: {
    nom: "Viande",
    fiche: "Aliments compostables",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/viande.png",
    synonyme:
      "Boeuf, mouton, poulet, veau, porc, jambon, steack haché, escalope",
  },
  Voilier: {
    nom: "Voilier",
    fiche: "Bateau",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/voilier.png",
    synonyme: "",
  },
  Voiture: {
    nom: "Voiture",
    fiche: "Voiture",
    icone: "https://oncle-stan.pacifiscan.org/icon-v2/voiture.png",
    synonyme:
      "Automobile, Break, Berline, Renault, Toyota, Ford, Peugeot, Hyunday, Peugeot, Citroen",
  },
};
