export default [
  { nom: "Aliments compostables", dechet: "Aliments compostables" },
  { nom: "Laitages", dechet: "Aliments compostables" },
  { nom: "Croutes de fromage", dechet: "Aliments compostables" },
  { nom: "Fanes de légumes", dechet: "Aliments compostables" },
  { nom: "Poisson (restes)", dechet: "Aliments compostables" },
  { nom: "Épluchures", dechet: "Aliments compostables" },
  { nom: "Fruits et légumes abîmés", dechet: "Aliments compostables" },
  { nom: "Marcs de café", dechet: "Aliments compostables" },
  { nom: "Sachets et feuilles de thés", dechet: "Aliments compostables" },
  { nom: "Ampoule", dechet: "Ampoule" },
  { nom: "Lampes", dechet: "Ampoule" },
  { nom: "Lumière", dechet: "Ampoule" },
  { nom: "Néon", dechet: "Ampoule" },
  { nom: "Appareil photo numérique", dechet: "Appareil photo numérique" },
  { nom: "Appareil photo", dechet: "Appareil photo numérique" },
  { nom: "Caméra", dechet: "Appareil photo numérique" },
  { nom: "Balai d'essuie-glace", dechet: "Balai d'essuie-glace" },
  { nom: "Essuie-glace", dechet: "Balai d'essuie-glace" },
  { nom: "Equipement automobile", dechet: "Balai d'essuie-glace" },
  { nom: "Pièce automobile", dechet: "Balai d'essuie-glace" },
  { nom: "Barquette en plastique", dechet: "Barquette en plastique" },
  { nom: "Barquette", dechet: "Barquette en plastique" },
  { nom: "Bateau", dechet: "Bateau" },
  { nom: "Scooter de mer", dechet: "Bateau" },
  { nom: "Bateau à moteur", dechet: "Bateau" },
  { nom: "Voilier", dechet: "Bateau" },
  { nom: "Catamaran", dechet: "Bateau" },
  { nom: "Vedette", dechet: "Bateau" },
  { nom: "Bateau de pêche promenade", dechet: "Bateau" },
  { nom: "Dériveur", dechet: "Bateau" },
  { nom: "Bateau pneumatique", dechet: "Bateau" },
  { nom: "Bateau semi-rigide", dechet: "Bateau" },
  { nom: "Batterie", dechet: "Batterie" },
  { nom: "Accumulateur", dechet: "Batterie" },
  { nom: "Batterie automobile", dechet: "Batterie automobile" },
  { nom: "Batterie au plomb", dechet: "Batterie automobile" },
  { nom: "Biberon en plastique", dechet: "Biberon en plastique" },
  { nom: "Biberon", dechet: "Biberon en plastique" },
  { nom: "Bidon d'huile de moteur", dechet: "Bidon d'huile de moteur" },
  { nom: "Bidon d'huile", dechet: "Bidon d'huile de moteur" },
  { nom: "Bijou", dechet: "Bijou" },
  { nom: "Collier", dechet: "Bijou" },
  { nom: "Montre", dechet: "Bijou" },
  { nom: "Bracelet", dechet: "Bijou" },
  { nom: "boucles d'oreille", dechet: "Bijou" },
  { nom: "piercing", dechet: "Bijou" },
  { nom: "Bocal en verre", dechet: "Bocal en verre" },
  { nom: "Pot de yaourt en verre", dechet: "Bocal en verre" },
  { nom: "Récipient en verre", dechet: "Bocal en verre" },
  { nom: "Bombe aérosol", dechet: "Bombe aérosol" },
  { nom: "Déodorant", dechet: "Bombe aérosol" },
  { nom: "Désodorisant", dechet: "Bombe aérosol" },
  { nom: "Bougie", dechet: "Bougie" },
  { nom: "Chandelle", dechet: "Bougie" },
  { nom: "Cierge", dechet: "Bougie" },
  { nom: "Bougie", dechet: "Bougie" },
  { nom: "Bouteille en métal", dechet: "Bouteille en métal" },
  { nom: "Bouteille de sirop en métal", dechet: "Bouteille en métal" },
  { nom: "Bouteille en plastique", dechet: "Bouteille en plastique" },
  { nom: "Bouteille d'eau", dechet: "Bouteille en plastique" },
  { nom: "Bouteille en verre", dechet: "Bouteille en verre" },
  { nom: "Bouteille d'eau (en verre)", dechet: "Bouteille en verre" },
  {
    nom: "Bouteille de sirop de médicament en verre (vide)",
    dechet: "Bouteille en verre",
  },
  { nom: "Boîte de conserve", dechet: "Boîte de conserve" },
  { nom: "Conserve", dechet: "Boîte de conserve" },
  { nom: "Boîte en métal", dechet: "Boîte en métal" },
  { nom: "Boîte de biscuit en métal", dechet: "Boîte en métal" },
  { nom: "Boîte en plastique", dechet: "Boîte en plastique" },
  { nom: "Boîte à fromage en plastique", dechet: "Boîte en plastique" },
  { nom: "Tupperware", dechet: "Boîte en plastique" },
  { nom: "Pochette alimentaire (en plastique)", dechet: "Boîte en plastique" },
  { nom: "Boîte à oeufs en carton", dechet: "Boîte à oeufs en carton" },
  { nom: "Boîte à fromage en carton", dechet: "Boîte à oeufs en carton" },
  { nom: "Brique alimentaire", dechet: "Brique alimentaire" },
  { nom: "Brique de lait", dechet: "Brique alimentaire" },
  { nom: "Brique de jus", dechet: "Brique alimentaire" },
  { nom: "Brique de soupe", dechet: "Brique alimentaire" },
  { nom: "Tetra pak", dechet: "Brique alimentaire" },
  { nom: "Brosse à dents", dechet: "Brosse à dents" },
  { nom: "Brosse à cheveux", dechet: "Brosse à dents" },
  { nom: "Café (marc)", dechet: "Café (marc)" },
  { nom: "Filtre à café", dechet: "Café (marc)" },
  { nom: "Cahier", dechet: "Cahier" },
  { nom: "Calepin", dechet: "Cahier" },
  { nom: "Bloc-notes", dechet: "Cahier" },
  { nom: "Carnet", dechet: "Cahier" },
  { nom: "Cahier à spirale", dechet: "Cahier" },
  { nom: "Calendrier", dechet: "Cahier" },
  { nom: "Canapé", dechet: "Canapé" },
  { nom: "Canapé-lit", dechet: "Canapé" },
  {
    nom: "Carte à puce (bancaire, de téléphone, d'identité)",
    dechet: "Carte à puce (bancaire, de téléphone, d'identité)",
  },
  {
    nom: "Carte SIM, carte RFID, carte bancaire",
    dechet: "Carte à puce (bancaire, de téléphone, d'identité)",
  },
  { nom: "Cartouche d'encre", dechet: "Cartouche d'encre" },
  { nom: "Cartouche d'impression", dechet: "Cartouche d'encre" },
  { nom: "CD/DVD", dechet: "CD/DVD" },
  { nom: "Blu-ray", dechet: "CD/DVD" },
  { nom: "CD-ROM", dechet: "CD/DVD" },
  { nom: "Disque (album)", dechet: "CD/DVD" },
  { nom: "CD", dechet: "CD/DVD" },
  { nom: "DVD", dechet: "CD/DVD" },
  { nom: "CDRom", dechet: "CD/DVD" },
  { nom: "Cassette", dechet: "CD/DVD" },
  { nom: "Chaussures", dechet: "Chaussures" },
  { nom: "Bottes", dechet: "Chaussures" },
  { nom: "Bottines", dechet: "Chaussures" },
  { nom: "Baskets", dechet: "Chaussures" },
  { nom: "Tennis", dechet: "Chaussures" },
  { nom: "Chaussons", dechet: "Chaussures" },
  { nom: "Pantoufles", dechet: "Chaussures" },
  { nom: "Savattes", dechet: "Chaussures" },
  { nom: "Souliers", dechet: "Chaussures" },
  { nom: "Après-ski", dechet: "Chaussures" },
  { nom: "Babouches", dechet: "Chaussures" },
  { nom: "Ballerines", dechet: "Chaussures" },
  { nom: "Boots", dechet: "Chaussures" },
  { nom: "Escarpins", dechet: "Chaussures" },
  { nom: "Mocassins", dechet: "Chaussures" },
  { nom: "Nu-pieds", dechet: "Chaussures" },
  { nom: "Tongs", dechet: "Chaussures" },
  { nom: "Sabots", dechet: "Chaussures" },
  { nom: "Sandales", dechet: "Chaussures" },
  { nom: "Snow-boot", dechet: "Chaussures" },
  { nom: "Ballerines", dechet: "Chaussures" },
  { nom: "Chewing-gum", dechet: "Chewing-gum" },
  { nom: "Bubble-gum", dechet: "Chewing-gum" },
  {
    nom: "Cosmétique (produit et emballage)",
    dechet: "Cosmétique (produit et emballage)",
  },
  {
    nom: "Fard (à paupières, à joues)",
    dechet: "Cosmétique (produit et emballage)",
  },
  { nom: "Mascara", dechet: "Cosmétique (produit et emballage)" },
  { nom: "Eyeliner", dechet: "Cosmétique (produit et emballage)" },
  { nom: "Fond de teint", dechet: "Cosmétique (produit et emballage)" },
  { nom: "Poudre", dechet: "Cosmétique (produit et emballage)" },
  { nom: "Blush", dechet: "Cosmétique (produit et emballage)" },
  { nom: "Anti-cernes", dechet: "Cosmétique (produit et emballage)" },
  { nom: "Couche-culotte", dechet: "Couche-culotte" },
  { nom: "Couches pour bébé", dechet: "Couche-culotte" },
  { nom: "Couches hygiéniques", dechet: "Couche-culotte" },
  { nom: "Tube de dentifrice", dechet: "Tube de dentifrice" },
  { nom: "Tube de crème", dechet: "Tube de dentifrice" },
  { nom: "Déchets verts", dechet: "Déchets verts" },
  { nom: "Tonte de pelouse", dechet: "Déchets verts" },
  { nom: "Tailles de haies", dechet: "Déchets verts" },
  { nom: "Tailles d'arbustes", dechet: "Déchets verts" },
  { nom: "Résidus d'élagage", dechet: "Déchets verts" },
  { nom: "Résidus de débroussaillement", dechet: "Déchets verts" },
  { nom: "Feuillages", dechet: "Déchets verts" },
  { nom: "Fleurs fânées", dechet: "Déchets verts" },
  { nom: "Feuilles mortes", dechet: "Déchets verts" },
  { nom: "Essuie-tout", dechet: "Essuie-tout" },
  { nom: "Papier absorbant", dechet: "Essuie-tout" },
  { nom: "Sopalin", dechet: "Essuie-tout" },
  { nom: "Feutre", dechet: "Feutre" },
  { nom: "Stabilo", dechet: "Feutre" },
  { nom: "Surligneur", dechet: "Feutre" },
  { nom: "Filtre à café", dechet: "Filtre à café" },
  { nom: "Café (marc)", dechet: "Filtre à café" },
  { nom: "Gobelet en carton", dechet: "Gobelet en carton" },
  { nom: "Verre en carton", dechet: "Gobelet en carton" },
  {
    nom: "Gobelet en plastique jetable",
    dechet: "Gobelet en plastique jetable",
  },
  { nom: "Verre en plastique", dechet: "Gobelet en plastique jetable" },
  { nom: "Gros électroménager", dechet: "Gros électroménager" },
  { nom: "Aspirateur", dechet: "Gros électroménager" },
  { nom: "Congélateur", dechet: "Gros électroménager" },
  { nom: "Freezer", dechet: "Gros électroménager" },
  { nom: "Lave-vaisselle", dechet: "Gros électroménager" },
  { nom: "Sèche-linge", dechet: "Gros électroménager" },
  { nom: "Hotte", dechet: "Gros électroménager" },
  { nom: "Plaque de cuisson", dechet: "Gros électroménager" },
  { nom: "Climatiseur", dechet: "Gros électroménager" },
  { nom: "Four", dechet: "Gros électroménager" },
  { nom: "Lave-linge", dechet: "Gros électroménager" },
  { nom: "Livre", dechet: "Livre" },
  { nom: "Bande-dessinée (album)", dechet: "Livre" },
  { nom: "Fruits et légumes abîmés", dechet: "Fruits et légumes abîmés" },
  { nom: "Poireaux", dechet: "Fruits et légumes abîmés" },
  { nom: "Fenouils", dechet: "Fruits et légumes abîmés" },
  { nom: "Carottes", dechet: "Fruits et légumes abîmés" },
  { nom: "Navets", dechet: "Fruits et légumes abîmés" },
  { nom: "Pommes de terre", dechet: "Fruits et légumes abîmés" },
  { nom: "Aubergines", dechet: "Fruits et légumes abîmés" },
  { nom: "Courgettes", dechet: "Fruits et légumes abîmés" },
  { nom: "Pommes", dechet: "Fruits et légumes abîmés" },
  { nom: "Oranges", dechet: "Fruits et légumes abîmés" },
  { nom: "Litchis", dechet: "Fruits et légumes abîmés" },
  { nom: "Bananes", dechet: "Fruits et légumes abîmés" },
  { nom: "Poires", dechet: "Fruits et légumes abîmés" },
  { nom: "Fraises", dechet: "Fruits et légumes abîmés" },
  { nom: "Framboises", dechet: "Fruits et légumes abîmés" },
  { nom: "Mandarine", dechet: "Fruits et légumes abîmés" },
  { nom: "Clémentine", dechet: "Fruits et légumes abîmés" },
  { nom: "Matériaux de construction", dechet: "Matériaux de construction" },
  { nom: "Brique", dechet: "Matériaux de construction" },
  { nom: "Tuile", dechet: "Matériaux de construction" },
  { nom: "Béton", dechet: "Matériaux de construction" },
  { nom: "Ciment", dechet: "Matériaux de construction" },
  { nom: "Parpaing", dechet: "Matériaux de construction" },
  { nom: "Fenêtre", dechet: "Matériaux de construction" },
  { nom: "Carrelage", dechet: "Matériaux de construction" },
  { nom: "Informatique", dechet: "Informatique" },
  { nom: "Fax", dechet: "Informatique" },
  { nom: "Scanner", dechet: "Informatique" },
  { nom: "Joystick", dechet: "Informatique" },
  { nom: "Trackpad", dechet: "Informatique" },
  { nom: "Disque dur externe", dechet: "Informatique" },
  { nom: "Console de jeu", dechet: "Informatique" },
  { nom: "Station d'accueil (informatique)", dechet: "Informatique" },
  { nom: "Dock", dechet: "Informatique" },
  { nom: "Clavier (informatique)", dechet: "Informatique" },
  { nom: "Souris (informatique)", dechet: "Informatique" },
  { nom: "Tour (informatique)", dechet: "Informatique" },
  { nom: "Unité centrale", dechet: "Informatique" },
  { nom: "Tablette numérique", dechet: "Informatique" },
  { nom: "Box internet", dechet: "Informatique" },
  { nom: "Tablette", dechet: "Informatique" },
  { nom: "Pc portable", dechet: "Informatique" },
  { nom: "Ordinateur", dechet: "Informatique" },
  { nom: "Jouet", dechet: "Jouet" },
  { nom: "Figurine", dechet: "Jouet" },
  { nom: "Peluche", dechet: "Jouet" },
  { nom: "Meuble", dechet: "Meuble" },
  { nom: "Etagère", dechet: "Meuble" },
  { nom: "Bibliothèque", dechet: "Meuble" },
  { nom: "Table basse", dechet: "Meuble" },
  { nom: "Cadre de lit", dechet: "Meuble" },
  { nom: "Placard", dechet: "Meuble" },
  { nom: "Buffet", dechet: "Meuble" },
  { nom: "Table de chevet", dechet: "Meuble" },
  { nom: "Chaise", dechet: "Meuble" },
  { nom: "Table", dechet: "Meuble" },
  { nom: "Eléments de cuisine", dechet: "Meuble" },
  { nom: "Lit", dechet: "Meuble" },
  { nom: "Tiroir", dechet: "Meuble" },
  { nom: "Tête de lit", dechet: "Meuble" },
  { nom: "Commode", dechet: "Meuble" },
  { nom: "Table à langer", dechet: "Meuble" },
  { nom: "Table de jardin", dechet: "Meuble" },
  { nom: "Chaise de jardin", dechet: "Meuble" },
  { nom: "Banc", dechet: "Meuble" },
  { nom: "Ilot central", dechet: "Meuble" },
  { nom: "Plan de travail", dechet: "Meuble" },
  { nom: "Vaisselier", dechet: "Meuble" },
  { nom: "Garde-manger", dechet: "Meuble" },
  { nom: "Coffre", dechet: "Meuble" },
  { nom: "Penderie", dechet: "Meuble" },
  { nom: "Fauteuil", dechet: "Meuble" },
  { nom: "Armoire", dechet: "Meuble" },
  { nom: "Guéridon", dechet: "Meuble" },
  { nom: "Micro-ondes", dechet: "Micro-ondes" },
  { nom: "Four micro-ondes", dechet: "Micro-ondes" },
  { nom: "Médicaments", dechet: "Médicaments" },
  { nom: "Sirop de médicament", dechet: "Médicaments" },
  { nom: "Gélules de médicament", dechet: "Médicaments" },
  { nom: "Comprimés de médicament", dechet: "Médicaments" },
  { nom: "Médocs", dechet: "Médicaments" },
  { nom: "Suppositoire", dechet: "Médicaments" },
  { nom: "Pommade de médicament", dechet: "Médicaments" },
  { nom: "Crème de médicament", dechet: "Médicaments" },
  { nom: "Collyre", dechet: "Médicaments" },
  { nom: "Pillule de médicament", dechet: "Médicaments" },
  { nom: "Cachet de médicament", dechet: "Médicaments" },
  { nom: "Spray de médicament", dechet: "Médicaments" },
  { nom: "Gouttes de médicament", dechet: "Médicaments" },
  { nom: "Patch de médicament", dechet: "Médicaments" },
  { nom: "Doliprane", dechet: "Médicaments" },
  { nom: "Papier", dechet: "Papier" },
  { nom: "Feuille", dechet: "Papier" },
  { nom: "Papier calque", dechet: "Papier" },
  { nom: "Petit électroménager", dechet: "Petit électroménager" },
  { nom: "Rice-cooker", dechet: "Petit électroménager" },
  { nom: "Bouilloire", dechet: "Petit électroménager" },
  { nom: "Grille-pain", dechet: "Petit électroménager" },
  { nom: "Toaster", dechet: "Petit électroménager" },
  { nom: "Ventilateur", dechet: "Petit électroménager" },
  { nom: "Mini-aspirateur", dechet: "Petit électroménager" },
  { nom: "Robot", dechet: "Petit électroménager" },
  { nom: "Mixeur", dechet: "Petit électroménager" },
  { nom: "Blender", dechet: "Petit électroménager" },
  { nom: "Cafetière", dechet: "Petit électroménager" },
  { nom: "Machine à café", dechet: "Petit électroménager" },
  { nom: "Couteau électrique", dechet: "Petit électroménager" },
  { nom: "Hachoir", dechet: "Petit électroménager" },
  { nom: "Fer à repasser", dechet: "Petit électroménager" },
  { nom: "Centrale vapeur", dechet: "Petit électroménager" },
  { nom: "Friteuse", dechet: "Petit électroménager" },
  { nom: "Grill", dechet: "Petit électroménager" },
  { nom: "Raclette", dechet: "Petit électroménager" },
  { nom: "Nettoyeur haute pression", dechet: "Petit électroménager" },
  { nom: "Karcher", dechet: "Petit électroménager" },
  { nom: "Batteur", dechet: "Petit électroménager" },
  { nom: "Rasoir électrique", dechet: "Petit électroménager" },
  { nom: "Caméscope", dechet: "Petit électroménager" },
  { nom: "Chaîne hi-fi", dechet: "Petit électroménager" },
  { nom: "Enceinte", dechet: "Petit électroménager" },
  { nom: "Radio-réveil", dechet: "Petit électroménager" },
  { nom: "Répondeur", dechet: "Petit électroménager" },
  { nom: "Jouet télécommandé", dechet: "Petit électroménager" },
  { nom: "Lampe torche", dechet: "Petit électroménager" },
  { nom: "Barbecue électrique", dechet: "Petit électroménager" },
  { nom: "Machine à coudre", dechet: "Petit électroménager" },
  { nom: "Magnétoscope", dechet: "Petit électroménager" },
  { nom: "Jouet électrique", dechet: "Petit électroménager" },
  { nom: "Scie sauteuse", dechet: "Petit électroménager" },
  { nom: "Radio", dechet: "Petit électroménager" },
  { nom: "Réveil matin", dechet: "Petit électroménager" },
  { nom: "Machine à pain", dechet: "Petit électroménager" },
  { nom: "Sèche-cheveux", dechet: "Petit électroménager" },
  { nom: "Télécommande", dechet: "Petit électroménager" },
  { nom: "Pot en plastique", dechet: "Pot en plastique" },
  { nom: "Pot de yaourt en plastique", dechet: "Pot en plastique" },
  { nom: "crème fraiche", dechet: "Pot en plastique" },
  { nom: "pot de creme", dechet: "Pot en plastique" },
  { nom: "Réfrigérateur", dechet: "Réfrigérateur" },
  { nom: "Frigidaire", dechet: "Réfrigérateur" },
  { nom: "Frigo", dechet: "Réfrigérateur" },
  { nom: "Sac poubelle", dechet: "Sac poubelle" },
  { nom: "Poubelle", dechet: "Sac poubelle" },
  { nom: "Sachet de thé", dechet: "Sachet de thé" },
  { nom: "Thé en sachet", dechet: "Sachet de thé" },
  { nom: "Stylo", dechet: "Stylo" },
  { nom: "Stylo bille", dechet: "Stylo" },
  { nom: "Téléphone mobile", dechet: "Téléphone mobile" },
  { nom: "Smartphone", dechet: "Téléphone mobile" },
  { nom: "Téléviseur", dechet: "Téléviseur" },
  { nom: "Télévision", dechet: "Téléviseur" },
  { nom: "TV", dechet: "Téléviseur" },
  { nom: "Ecran", dechet: "Téléviseur" },
  { nom: "Moniteur PC", dechet: "Téléviseur" },
  { nom: "Vaisselle", dechet: "Vaisselle" },
  { nom: "Tasse", dechet: "Vaisselle" },
  { nom: "Mug", dechet: "Vaisselle" },
  { nom: "Fourchette", dechet: "Vaisselle" },
  { nom: "Cuillère", dechet: "Vaisselle" },
  { nom: "Assiette", dechet: "Vaisselle" },
  { nom: "Casserole", dechet: "Vaisselle" },
  { nom: "Bol", dechet: "Vaisselle" },
  { nom: "Voiture", dechet: "Voiture" },
  { nom: "VHU", dechet: "Voiture" },
  { nom: "Voiture", dechet: "Voiture" },
  { nom: "Véhicule (automobile)", dechet: "Voiture" },
  { nom: "Automobile", dechet: "Voiture" },
  { nom: "Vélo", dechet: "Vélo" },
  { nom: "Cycle", dechet: "Vélo" },
  { nom: "Bicyclette", dechet: "Vélo" },
  { nom: "Bécane (biclou)", dechet: "Vélo" },
  { nom: "Tandem", dechet: "Vélo" },
  { nom: "Vêtement", dechet: "Vêtement" },
  { nom: "Pull", dechet: "Vêtement" },
  { nom: "T-shirt", dechet: "Vêtement" },
  { nom: "Pantalon", dechet: "Vêtement" },
  { nom: "Short", dechet: "Vêtement" },
  { nom: "Bermuda", dechet: "Vêtement" },
  { nom: "Pantacourt", dechet: "Vêtement" },
  { nom: "Maillot de bain", dechet: "Vêtement" },
  { nom: "Chaussettes", dechet: "Vêtement" },
  { nom: "Bonnet", dechet: "Vêtement" },
  { nom: "Gant", dechet: "Vêtement" },
  { nom: "Echarpe", dechet: "Vêtement" },
  { nom: "Chemise", dechet: "Vêtement" },
  { nom: "Polo", dechet: "Vêtement" },
  { nom: "Veste", dechet: "Vêtement" },
  { nom: "Costume", dechet: "Vêtement" },
  { nom: "Gilet", dechet: "Vêtement" },
  { nom: "Sweat", dechet: "Vêtement" },
  { nom: "Caleçon", dechet: "Vêtement" },
  { nom: "Slip", dechet: "Vêtement" },
  { nom: "Boxer", dechet: "Vêtement" },
  { nom: "Caban", dechet: "Vêtement" },
  { nom: "Duffle-coat", dechet: "Vêtement" },
  { nom: "Trench", dechet: "Vêtement" },
  { nom: "Legging", dechet: "Vêtement" },
  { nom: "Jupe", dechet: "Vêtement" },
  { nom: "Robe", dechet: "Vêtement" },
  { nom: "Collant", dechet: "Vêtement" },
  { nom: "Mouffle", dechet: "Vêtement" },
  { nom: "Mitaine", dechet: "Vêtement" },
  { nom: "Foulard", dechet: "Vêtement" },
  { nom: "Sous-vêtement", dechet: "Vêtement" },
  { nom: "Lingerie", dechet: "Vêtement" },
  { nom: "Culotte", dechet: "Vêtement" },
  { nom: "Manteau", dechet: "Vêtement" },
  { nom: "Soutien-gorge", dechet: "Vêtement" },
];
