export const points = {
  decheterieGadji: {
    name: "Déchetterie Gadji",
    phone: "010203",
    description:
      "La déchetterie Gadji est située ... Elle dispose d'un espace de stockage de déchets et d'un espace de compostage",
    icon: logo,
  },
  decheterieDucos: {
    name: "Déchetterie de Ducos",
    phone: "010203",
    description:
      "Adipisicing Lorem cupidatat duis deserunt enim ex veniam veniam in.",
    icon: logo,
  },
  decheterieMagenta: {
    name: "Déchetterie de Magenta",
    phone: "010203",
    description: "Sint laboris ut excepteur occaecat ipsum nostrud.e",
    icon: logo,
  },
  decheterie4: {
    name: "Déchetterie du 6ème km",
    phone: "010203",
    description: "Sint laboris ut excepteur occaecat ipsum nostrud.e",
    icon: logo,
  },
};

const anxious = require("../../assets/emoji/anxious.png");
const worried = require("../../assets/emoji/worried.png");
const love = require("../../assets/emoji/love.png");
const logo = require("../../assets/icon.png");

export const wastesType = {
  Ampoule: {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Ampoule sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Arme à feu": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Arme à feu sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Balai d'essuie-glace": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'un Balai d'essuie-glace sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Barquette en aluminium": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Barquette en aluminium sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Barquette en plastique": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Barquette en plastique sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Batterie de téléphone": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Batterie de téléphone sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Batterie de voiture": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Batterie de voiture sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Boite d'oeuf": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Boite d'oeuf sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Boite de conserve": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Boite de conserve sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Boite de pizza": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Boite de pizza sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Boite en métal": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Boite en métal sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Boite en plastique": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Boite en plastique sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Bombe aerosol": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Bombe aerosol sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Bouchon en liège": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'un Bouchon en liège sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Bouteille de détergent": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Bouteille de détergent sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Bouteille en métal": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Bouteille en métal sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Bouteille en plastique": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Bouteille en plastique sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Bouteille en verre": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Bouteille en verre sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  Canette: {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Canette sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Capsule de café": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Capsule de café sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  Carton: {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'un Carton sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Cartouche d'encre": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Cartouche d'encre sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  Cigarette: {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Cigarette sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Déchets vers": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact des Déchets vers sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  Electronique: {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'un déchet Electronique sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Feuille d'aluminium": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Feuille d'aluminium sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Film plastique": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'un Film plastique sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Filtre à café": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'un Filtre à café sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Flacon en plastique": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'un Flacon en plastique sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Fruits et légumes": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact de Fruits et légumes sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Gobelet en plastique": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'un Gobelet en plastique sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Gros électroménager": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact du Gros électroménager sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  Jouet: {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'un Jouet sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  Journal: {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'un Journal sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Marc de café": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact de Marc de café sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  Masque: {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'un Masque sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  Meuble: {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'un Meuble sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  Mouchoir: {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'un Mouchoir sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  Paille: {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Paille sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  Pile: {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une Pile sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  Pneu: {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'un Pneu sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Sac cabas en plastique": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'un Sac cabas en plastique sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Sac plastique biodégradable": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'un Sac plastique biodégradable sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Sac poubelle": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'un Sac poubelle sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  Stylo: {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'un Stylo sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Tetra pak": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact d'une brique Tetra pak sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  Vaisselle: {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact de la vaisselle sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  Vêtements: {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact de vêtements sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
  "Petit électroménager": {
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    endroit: [
      "decheterieGadji",
      "decheterieDucos",
      "decheterieMagenta",
      "decheterie4",
    ],
    Header: "Impact du Petit électroménager sur l'environnement",
    image: logo,
    eviterSmiley: anxious,
    quefaireSmiley: worried,
    impactSmiley: love,
    anneeDecomposition: 50,
    eviterTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    impactTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    poids: 0.4,
    quefaireTexte: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    smallText: "Très commun",
    sources: "Wikipédia",
  },
};

export const associationApi = {
  Light: "Ampoule",
  Firearm: "Arme à feu",
  "Wiper blade": "Balai d'essuie-glace",
  "Aluminum tray": "Barquette en aluminium",
  "Plastic container": "Barquette en plastique",
  "Phone battery": "Batterie de téléphone",
  "Automotive battery": "Batterie de voiture",
  "Egg box": "Boite d'oeuf",
  "Tin can": "Boite de conserve",
  "Pizza box": "Boite de pizza",
  "Metal box": "Boite en métal",
  "Plastic box": "Boite en plastique",
  "Spray can": "Bombe aerosol",
  "Cork stoppers": "Bouchon en liège",
  "Detergent bottle": "Bouteille de détergent",
  "Metal bottle": "Bouteille en métal",
  "Plastic bottle": "Bouteille en plastique",
  "Glass bottle": "Bouteille en verre",
  Bobbin: "Capsule de café",
  "Coffee capsules": "Capsule de café",
  Cardboard: "Carton",
  "Ink cartridge": "Cartouche d'encre",
  Cigarette: "Cigarette",
  "Green waste": "Déchets vers",
  Electronic: "Electronique",
  "Aluminum foil": "Feuille d'aluminium",
  "Plastic film": "Film plastique",
  "Coffee filter": "Filtre à café",
  "Fruits and vegetables": "Fruits et légumes",
  "Plastic cup": "Gobelet en plastique",
  "Large household appliances": "Gros électroménager",
  Toy: "Jouet",
  Newspaper: "Journal",
  Coffee: "Marc de café",
  Mask: "Masque",
  Furniture: "Meuble",
  Tissue: "Mouchoir",
  Straw: "Paille",
  "Small appliance": "Petit électroménager",
  "Disposable battery": "Pile",
  Tire: "Pneu",
  "Plastic tote bag": "Sac cabas en plastique",
  "Biodegradable plastic bag": "Sac plastique biodégradable",
  "Garbage bag": "Sac poubelle",
  Pen: "Stylo",
  "Tetra Pak": "Tetra pak",
  "Porcelain tableware": "Vaisselle",
  Clothes: "Vêtements",
};

export const getKeys = () => {
  return Object.keys(wastesType);
};
